---
# tasks file for fermyon

# Checkout installer
- name: Prepare fermyon
  block:
    - name: Ensure Hippo Url is present in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        insertafter: '^127.0.0.1	localhost'
        line: "127.0.0.1  hippo.local.fermyon.link"
    - name: Ensure group "admin" exists
      ansible.builtin.group:
        name: admin
        state: present
    - name: Add the user 'fermyon' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: fermyon
        comment: fermyon
        group: admin
        system: true
        home: "{{ fermyon_installation }}"
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ fermyon_installation }}"
        state: directory
        mode: '0755'
        owner: fermyon
    - name: Ensuring that admin group is able to use sudo without password
      lineinfile:
        path: /etc/sudoers
        regexp: '^%admin'
        line: '%admin ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Change directory ownership
      ansible.builtin.file:
        path: "{{ fermyon_installation }}"
        owner: fermyon
        recurse: true
        state: directory
    - name: consul | Create start file
      template: "src=start.sh.j2 dest={{ fermyon_installation }}/start.sh"
    - name: Make file exeutable
      ansible.builtin.file:
        path: "{{ fermyon_installation }}/installer/local/start.sh"
        mode: '0744'
    # create as service
    - name: Fermyon | Create environment file
      template: "src=fermyon.env.j2 dest={{ fermyon_installation }}/fermyon.conf"
    - name: Fermyon | Create Unit file
      template: src=fermyon.service.j2 dest=/lib/systemd/system/fermyon.service mode=644
      notify:
        - fermyon.restart
    - name: Fermyon | Start Fermyon
      service: name=fermyon.service state=started enabled=yes