---
# tasks file for fermyon

# Add Hashicorp repo
- name: Add Hashicorp repo
  block:
    - name: Hashicorp |add apt key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Hashicorp | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
# Install nomad
- name: Update repositories cache and install "nomad" package
  ansible.builtin.apt:
    name: nomad
    update_cache: yes
# Install consul
- name: Update repositories cache and install "consul" package
  ansible.builtin.apt:
    name: consul
    update_cache: yes
# Install git
- name: Update repositories cache and install "git" package
  ansible.builtin.apt:
    name: git
    update_cache: yes
# Install spin
- name: Install spin
  block:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - build-essential 
        - libssl-dev 
        - pkg-config
        - curl
    - name: Donwload Spin
      ansible.builtin.get_url:
        url: https://developer.fermyon.com/downloads/install.sh
        dest: /tmp/
        mode: "744"
    - name: Execute Installer
      ansible.builtin.shell: /tmp/install.sh
      args:
        chdir: /tmp/
    - name: mv spin
      ansible.builtin.shell: 
        cmd: mv /tmp/spin /usr/local/bin/
        chdir: /tmp/

# Checkout installer
- name: Prepare fermyon
  block:
    - name: Add the user 'fermyon' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: fermyon
        comment: fermyon
        system: true
        home: "{{ fermyon_installation }}"
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ fermyon_installation }}"
        state: directory
        mode: '0755'
        owner: fermyon
    - name:  Git checkout
      ansible.builtin.git:
        #repo: 'https://github.com/fermyon/installer.git'
        repo: https://github.com/hurzelpurzel/installer.git
        dest: "{{ fermyon_installation }}/installer"
        version: main
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: "{{ fermyon_installation }}/installer/local/start.sh"
        owner: fermyon
        mode: '0744'
    # create as service
    - name: Fermyon | Create environment file
      template: src=fermyon.env.j2 dest=/etc/sysconfig/fermyon
    - name: Fermyon | Create Unit file
      template: src=fermyon.service.j2 dest=/lib/systemd/system/fermyon.service mode=644
      notify:
        - reload systemctl
    - name: Fermyon | Start Fermyon
      service: name=fermyon.service state=started enabled=yes